FROM docker.maceroc.com/millegrilles_python_base:1.39.2

ADD . /opt/src

RUN cd /opt/src/python && \
    pip3 install -r requirements.txt && \
    python3 setup.py install && \
    \
    cd / \
    rm -rf /opt/src
