FROM docker.maceroc.com/millegrilles_consignation_python_main:1.32.1

ADD . /opt/src

RUN cd /opt/src/python && \
    pip3 install -r requirements.txt && \
    python3 setup.py install && \
    \
    cd / \
    rm -rf /opt/src
