FROM rpi38

ARG VERSION_MILLEGRILLES=1.31

ADD . /opt/src

RUN mkdir -p /opt/src/tmp && \
    cd /opt/src && \
    git -C /opt/src/tmp clone -b $VERSION_MILLEGRILLES --single-branch https://github.com/dugrema/millegrilles.consignation.python.git && \
    \
    cd /opt/src/tmp/millegrilles.consignation.python && \
    pip3 install -r requirements.txt && \
    python3 setup.py install && \
    \
    cd /opt/src/python && \
    pip3 install -r requirements.txt && \
    python3 setup.py install

